# 1

In [ ]:
import pandas as pd  

data = {'Name': ['Alice', 'Bob', 'Charlie'], 
        'Age': [25, 30, 'Thirty-Five'],  
        'Gender': ['F', 'M', 'M']}  

df = pd.DataFrame(data)

average_age = df['Age'].mean()

print(f"Average Age: {average_age}")


In [ ]:
TypeError: expected a number, got str

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [2]:
import pandas as pd  

data = {'Name': ['Alice', 'Bob', 'Charlie'], 
        'Age': [25, 30, 35],  
        'Gender': ['F', 'M', 'M']}  

df = pd.DataFrame(data)

average_age = df['Age'].mean()

print(f"Average Age: {average_age}")


Average Age: 30.0


# 2

In [ ]:
import numpy as np

data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

q1, q3 = np.percentile(data, 25, 75)

q1, q3

In [ ]:
AxisError                                 

In [5]:
import numpy as np

data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

q1, q3 = np.percentile(data, [25, 75])

q1, q3

(np.float64(3.25), np.float64(7.75))

# 3

In [ ]:
import numpy as np
from scipy.stats import zscore

data = [1, 2, 3, 100, 5, 6, 7, 8, 9]

outliers = [i for i in data if zscore(data) > 2]

In [ ]:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
import numpy as np
from scipy.stats import zscore

data = [1, 2, 3, 100, 5, 6, 7, 8, 9]

for i in data:
    print(i)
    # if zscore(data) > 2:
    print(data.index(i))
    if zscore(data)[data.index(i)] > 2:
        print(f"Outlier detected: {i}")


1
0
2
1
3
2
100
3
Outlier detected: 100
5
4
6
5
7
6
8
7
9
8


# 4

In [17]:
from scipy.stats import norm

pdf_val = norm.pdf(2, 0, -1)
pdf_val


np.float64(nan)

In [ ]:
norm.pdf(x, loc=0, scale=1)
Because the standard deviation is negative.

In norm.pdf(x, mean, std), the standard deviation must be positive.
You used -1, which is not allowed, so SciPy returns NaN.

Use a positive value instead, like 1.


In [18]:
from scipy.stats import norm

pdf_val = norm.pdf(2, 0, 1)
pdf_val


np.float64(0.05399096651318806)

# 5

In [ ]:
import seaborn as sns
import pandas as pd

df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
sns.pairplot(df, hue='C')


In [ ]:
KeyError: 'C'

In [18]:
import seaborn as sns
import pandas as pd

df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6], 'C': ['X', 'Y', 'Z']})
sns.pairplot(df, hue='C')


# 6

In [ ]:
import numpy as np

x = [1, 2, 3, 4]
y = [2, 4, 6, 8]

cov_matrix = np.cov()


In [ ]:
TypeError: cov() missing 1 required positional argument:

cov means covariance requires 2 colummns to compare
cov(x,y)

In [ ]:
import numpy as np

x = [1, 2, 3, 4]
y = [2, 4, 6, 8]

cov_matrix = np.cov(x, y)
cov_matrix

# 7

In [ ]:
import numpy as np

data = [2, 4, 6, 8, 10]

mean_value = mean(data)
print(f"Mean: {mean_value}")


In [ ]:
NameError: mean is not defined

In [13]:
import numpy as np

data = [2, 4, 6, 8, 10]

mean_value = np.mean(data)
print(f"Mean: {mean_value}")


Mean: 6.0


# 8

In [19]:
import pandas as pd
import numpy as np

data = {'A': [1, 2, np.nan, 4], 'B': [np.nan, 5, 6, np.nan]}
df = pd.DataFrame(data)

df.replace(np.nan, 0, inplace=False)  
print(df)

     A    B
0  1.0  NaN
1  2.0  5.0
2  NaN  6.0
3  4.0  NaN


In [ ]:
inplace = True to modify the original df
inplace = False creates a copy without changing df


In [20]:
import pandas as pd
import numpy as np

data = {'A': [1, 2, np.nan, 4], 'B': [np.nan, 5, 6, np.nan]}
df = pd.DataFrame(data)

df.replace(np.nan, 0, inplace=True)  
print(df)

     A    B
0  1.0  0.0
1  2.0  5.0
2  0.0  6.0
3  4.0  0.0


In [ ]:
import numpy as np
import pandas as pd

data = {'A': [1, 2, 3, 4], 'B': [5, 6, 7, 8]}
df = pd.DataFrame(data)

correlation = np.corrcoef()
print("Correlation:\n", correlation)


In [ ]:
TypeError: corrcoef() missing 1 required positional argument: 'x'

In [11]:
import numpy as np
import pandas as pd

data = {'A': [1, 2, 3, 4], 'B': [5, 6, 7, 8]}
df = pd.DataFrame(data)

correlation = np.corrcoef(df['A'], df['B'])
print("Correlation:\n", correlation)

correlation = np.corrcoef(df)
print("Correlation:\n", correlation)

Correlation:
 [[1. 1.]
 [1. 1.]]
Correlation:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
